export const GET_TOURS_REQUEST = 'GET_TOURS_REQUEST';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_FAILURE = 'GET_TOURS_FAILURE';
export const GET_CURRENT_TOUR_REQUEST = 'GET_CURRENT_TOUR_REQUEST';
export const GET_CURRENT_TOUR_SUCCESS = 'GET_CURRENT_TOUR_SUCCESS';
export const GET_CURRENT_TOUR_FAILURE = 'GET_CURRENT_TOUR_FAILURE';
export const GET_FILTER_TEXT = 'GET_FILTER_TEXT';
